version: '3'

services:

#  nodejs:
#    build:
#      context: .
#      dockerfile: ./node/Dockerfile
#    container_name: nodejs
#    volumes:
#      - ./server:/usr/app/server
#    ports:
#      - "3009:3009"
#    command: npm run up --prefix server/
#    networks:
#      mongodb-connection:
#        ipv4_address: 172.22.0.107
        
  mongo:
    image: mongo
    container_name: mongodb-local
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - ./mongo_basic.js:/docker-entrypoint-initdb.d/mongo_basic.js:ro
      - ./mongo-volume:/data/db
    networks:
      mongodb-connection:
        ipv4_address: 172.22.0.101

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb-local
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=example
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=example
    networks:
      mongodb-connection:
        ipv4_address: 172.22.0.102

networks:
  mongodb-connection:
    ipam:      
      driver: default
      config:
        - subnet: 172.22.0.0/16
